#Per log e thread info decommentare i seguenti

#CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_THREAD_NAME=y
#CONFIG_THREAD_ANALYZER=y
#CONFIG_THREAD_ANALYZER_USE_LOG=y
#CONFIG_THREAD_ANALYZER_AUTO=y
#CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=10
#CONFIG_THREAD_RUNTIME_STATS=y

CONFIG_INIT_STACKS=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_SENSOR=y
CONFIG_ADC=y
CONFIG_MAIN_STACK_SIZE=768

#Alterna tra i vari moduli commentando/decommentando.
#CONFIG_APP_MODULE_COUNTDOWN=y
#CONFIG_APP_MODULE_BLINK=y
#CONFIG_APP_MODULE_BUTTON_I=y
CONFIG_APP_MODULE_TEMP=y
#CONFIG_APP_MODULE_THREAD=y
