CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_SENSOR=y
CONFIG_ADC=y

#Alterna tra i vari moduli commentando/decommentando.
#CONFIG_APP_MODULE_COUNTDOWN=y
#CONFIG_APP_MODULE_BLINK=y
#CONFIG_APP_MODULE_BUTTON_I=y
CONFIG_APP_MODULE_TEMP=y
